spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
project:
  bundles:
    home: http://localhost:3000/js/home_bundle.js
  encryption:
    password: hello123
  redirectUrl: http://localhost:8080/login/auth
